name: Node.js CI

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: back ci
      run: npm --prefix ./refrigerator_label_back/ ci
    - name: back build
      run: npm --prefix ./refrigerator_label_back/ run build --if-present
    - name: front ci
      run: npm --prefix ./refrigerator_label_front/ ci
    - name: front build
      run: npm --prefix ./refrigerator_label_front/ run build --if-present
    - name: front test
      run: npm --prefix ./refrigerator_label_front/ test
