name: Refrigerator_Label CI/CD

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build_front:
    name: build_front
    runs-on: self-hosted
     
    strategy:
      matrix:
        node-version: [17.x]
        
    environment: staging 
    
    env:
      REACT_APP_BACK_END: ${{secrets.REACT_APP_BACK_END}}
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: front ci
      run: npm --prefix ./refrigerator_label_front/ ci
    - name: front test
      run: npm --prefix ./refrigerator_label_front/ test
    - name: front build
      run: npm --prefix ./refrigerator_label_front/ run build --if-present
    - name: front ssh
      run: rsync -avz -e 'ssh' ./refrigerator_label_front/build ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
  
  build_back:
    name: build_back
    runs-on: self-hosted
     
    strategy:
      matrix:
        node-version: [17.x]
        
    environment: staging 
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'create back env file'
        run: |
          cat <<EOF > .env
          aws_host="123123"
          aws_port="213"
          aws_pw="123"
          aws_user="123"
          dbname="123"
          EOF
      - name: back ci
        run: npm --prefix ./refrigerator_label_back/ ci
